

services:
  mysql:
    image: mysql:8.0
    container_name: wso2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: shared_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      # MySQL esegue automaticamente gli script in questa cartella all'avvio
      #- ./db_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-manager:
    image: wso2/wso2am:4.3.0
    container_name: wso2am-mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8280:8280"
      - "8243:8243"
      - "9443:9443"
    volumes:
      # Montiamo il file di configurazione
      - ./deployment.toml:/home/wso2carbon/wso2am-4.3.0/repository/conf/deployment.toml:ro
      # Montiamo il driver MySQL
      - ./mysql-connector-j-8.0.33.jar:/home/wso2carbon/wso2am-4.3.0/repository/components/lib/mysql-connector-j-8.0.33.jar:ro
    entrypoint: >
      sh -c "ln -s /home/wso2carbon/wso2am-4.3.0/repository/resources/dbscripts /home/wso2carbon/wso2am-4.3.0/dbscripts && /home/wso2carbon/docker-entrypoint.sh"
    environment:
      - JVM_MEM_OPTS=-Xms1024m -Xmx2048m #-Dsetup