version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: WSO2AM_DB
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api-manager:
    image: wso2/wso2am:4.3.0
    container_name: wso2am
    ports:
      - "9443:9443" # Console (Carbon, Publisher, DevPortal)
      - "8280:8280" # Gateway HTTP
      - "8243:8243" # Gateway HTTPS
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./conf/deployment.toml:/home/wso2carbon/wso2am-4.3.0/repository/conf/deployment.toml
      - ./lib/mysql-connector-j-8.0.33.jar:/home/wso2carbon/wso2am-4.3.0/repository/components/lib/mysql-connector-j-8.0.33.jar
    environment:
      - NODE_IP=127.0.0.1