[server]
hostname = "localhost"
node_ip = "127.0.0.1"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?useSSL=false&allowPublicKeyRetrieval=true"
username = "root"
password = "root_password"
driver = "com.mysql.cj.jdbc.Driver"
validation_query = "SELECT 1"

# Configurazione per la gestione degli utenti (User Store)
[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?useSSL=false&allowPublicKeyRetrieval=true"
username = "root"
password = "root_password"
driver = "com.mysql.cj.jdbc.Driver"
validation_query = "SELECT 1"